### ISSUE TITLE
Add-ons don't seem to work properly on web panels

### ISSUE THREAD

**Issue by duckaleuze** [aminought/firefox-second-sidebar#2]
ublock origin: 
![image](https://github.com/user-attachments/assets/27e2a892-9e49-4103-8520-ce72cff4934d)

[Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/)
![image](https://github.com/user-attachments/assets/c9df8877-e870-40f3-9d02-f5007f1afb2a)

it would be great if addons could work on webpanels so I can block trackers, style sites with stylus and more, I'm in love with this project btw, keep it up!

**Comment by aminought** [comment]
Thank you for feature request. I'm not sure if I can do this. My web panels are very lightweight, much lighter than Floorp's, because they don't use tabs. It seems that tabs are necessary for extensions to function properly.

**Comment by GunGunGun** [comment]
Yeah, using hidden tab is probably the only way to make extensions/addons work.

I think it worths the trade offs, the sidebar is intentionally made to not allow extensions/addons to work with, but it was such an outdated standards and should be changed long time ago because back then sidebar didn't do much, but nowadays devs push sidebar to its limit so being able to use important addons like uBlockOrigin is pretty useful, especially on Youtube.

Also your sidebar codebase is beautiful, just want to say that because it's perfect.

**Comment by aminought** [comment]
> I think it worths the trade offs

I agree with you, so I will try to integrate tabs. Initially, I didn't really want to do this, because even in Floorp you can see how these hidden tabs appear and immediately disappear, it's annoying. Maybe I can somehow overcome this problem, or I won't face it at all.

> Also your sidebar codebase is beautiful, just want to say that because it's perfect.

Thank you! Before yesterday's refactoring, it was a mess. To be honest, I still don't like my code in some places...

**Comment by aminought** [comment]
I have good news! I have implemented support for WebExtensions (#7), but I still need some time for testing. You will help me a lot if you try to install the script from branch [webextensions-support](https://github.com/aminought/firefox-second-sidebar/tree/webextensions-support). 👉👈

**Comment by GunGunGun** [comment]
Sure, will test it in Zen!

**Comment by GunGunGun** [comment]
I just tested it and it looks like addons work fine, just some 2nd sidebar's toolbarbutton display issues (Zen) but no problem:

![image](https://github.com/user-attachments/assets/f8de66d9-04de-4893-b6a7-d312240bd34c)

**Comment by duckaleuze** [comment]
hey I just tested it and extensions works great! but there's a bug https://github.com/aminought/firefox-second-sidebar/issues/9

**Comment by aminought** [comment]
> hey I just tested it and extensions works great! but there's a bug #9

Thank you, but don't create new issues wit problems that are not related to the main branch, please. You can leave a comment here and I'll be happy to take a look.

**Comment by duckaleuze** [comment]
I'm sorry I'm not really sure how github works, my apoligies, do you want me to report the bug here again?

**Comment by aminought** [comment]
I believe I have resolved the issues with the tabs and sound indicator.

**Comment by aminought** [comment]
#7 is merged into master, I'm closing this issue.
